version: 2.1

jobs:
  build:
    docker:
      - image: google/dart:latest
    environment:
      FLUTTER_HOME: /usr/lib/flutter
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - deploy:
          name: Publish APK
          command: |
            # Insert commands to publish APK to the appropriate distribution channel
            # Example: curl -X POST -F "apk=@path/to/apk" https://example.com/publish

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
